version: "3.8"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app            # Code-Mount für Live-Reload im Development
    environment:
      FLASK_APP: app
      FLASK_ENV: development
